### ISSUE TITLE
Impossible to deploy to azure

### ISSUE THREAD

**Issue by nigel-dewar** [OfficeDev/SP-AngularJS-ExpenseManager-Code-Sample#1]
Hi This works great in development but impossible to deploy to azure.

Not sure what the issue is. I have deployed several mvc and web api sites to azure that use azure ad ( with databases ) but for some reason this project will not.

**Comment by DanWahlin** [comment]
Hi Nigel. I've never tried to deploy it to Azure so I'm afraid I don't know on that one. It's intended to be a prototype project run locally at this point. If you do happen to see anything that should be changed to move to Azure definitely let me know though...interested in what would prevent that from happening.

**Comment by nigel-dewar** [comment]
Hi Dan, 

Yeah no worries mate, I’ll keep cracking away on it. It’s the things I find with Azure. A LOT of hassles despite the propaganda. I find it painful to work with vs most other cloud systems, even the small ones. 

Cheers

Nigel

**Comment by DanWahlin** [comment]
Thanks! Appreciate hearing about anything you find. That's definitely strange. :-)
