### ISSUE TITLE
Query - Why use handler.ashx - why not use API controller to call SP

### ISSUE THREAD

**Issue by nigel-dewar** [OfficeDev/SP-AngularJS-ExpenseManager-Code-Sample#3]
Hi Dan.

Thanks so much for this example. this repo continues to be one I come back to for reference. They way you put this project together is really clever.

I have a query: Why the handler.ashx? Why not use an API controller to do the comms to sharepoint?

**Comment by DanWahlin** [comment]
Thanks. I don't remember the specific reason (this is an older project now) but at the time it was much easier to use an ashx vs. an API controller due to some specific constraints we had. Wish I remembered the specifics.

**Comment by nigel-dewar** [comment]
No probs. Thanks Dan.
